import { useEffect } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { handleFirestoreError, OperationType } from "@/firebase";
import { useAuth } from "@/hooks/useAuth";
import { toast } from "sonner";
import { smartDb } from "@/lib/localDb";
import { Student, Staff } from "@/types";
import { sendInvoiceEmail, sendInvoiceGeneratedEmail } from "@/lib/emailService";
import { useFinancialSettings } from "@/hooks/useFinancialSettings";
import { createDefaultFeeCalculator } from "@/services/fee/FeeCalculator";
import { FeeDiscountDefinition, ScholarshipRecord } from "@/services/fee/FeeRuleStrategy";

export interface FeeStructure {
  id: string;
  name: string;
  classId: string;
  className: string;
  academicYear: string;
  totalAmount: number;
  components: {
    name: string;
    amount: number;
    isOptional: boolean;
  }[];
  status: 'Active' | 'Inactive';
  uid: string;
  createdAt: string | Date;
  // Absent/undefined == regular tuition structure (existing behaviour,
  // unchanged). "Admission"/"SchoolFee" structures are one-off fees a
  // finance user generates a single invoice from for one admissions lead,
  // via generateSingleInvoice — never bulk-generated by class. "Hostel" is
  // looked up automatically on room allocation (createHostelFeeInvoice).
  // No "Transport" here deliberately — Transport invoices are generated
  // directly from the real per-student monthlyFee already on the
  // allocation record, never from a central FeeStructure.
  feeType?: 'Tuition' | 'Admission' | 'SchoolFee' | 'Hostel';
}

export interface FeeDiscount {
  id: string;
  name: string;
  type: 'Percentage' | 'Fixed';
  value: number;
  category: 'Scholarship' | 'Sibling' | 'Early Bird' | 'Staff Child' | 'Other';
  status: 'Active' | 'Inactive';
  uid: string;
  createdAt: string | Date;
}

export interface Invoice {
  id: string;
  invoiceNumber: string;
  studentId: string;
  studentName: string;
  classId: string;
  className: string;
  category: string;
  term?: string; // e.g. "Term 1" — set when the fee structure has term-labeled components
  termNumber?: number;
  amount: number;
  paidAmount: number;
  dueAmount: number;
  dueDate: string;
  status: 'Unpaid' | 'Partial' | 'Paid' | 'Overdue' | 'Cancelled';
  penalty: number;
  uid: string;
  createdAt: string | Date;
  // Absent == regular tuition invoice (existing behaviour, unchanged).
  feeType?: 'Tuition' | 'Admission' | 'SchoolFee' | 'Transport' | 'Hostel' | 'Exam';
  // Set only on Admission/SchoolFee invoices — ties the invoice back to the
  // Admissions Lead it was generated for, so paying it in full can advance
  // that lead's pipeline stage automatically. See advanceLeadOnFeeInvoicePaid.
  linkedLeadId?: string;
  // Set when the parent completes the simulated payment step on the
  // admission form's end page (card/bank/cash) — a declaration only, not a
  // confirmed payment. Finance still has to verify the transaction (or
  // collect the cash) and mark it Paid in Fees Management → Admission Fees.
  paymentSubmittedByParent?: boolean;
  paymentSubmittedAt?: string;
  paymentMethodDeclared?: string;
  paymentTxnRef?: string;
}

/**
 * Display-only status: "Upcoming" isn't a stored invoice status — it's derived
 * here so a term invoice whose due date hasn't arrived yet reads as "not due
 * yet" instead of a scary "Unpaid"/"Overdue", without touching the real
 * status field used by payment/penalty logic elsewhere.
 */
export function getInvoiceDisplayStatus(invoice: Invoice): 'Paid' | 'Partial' | 'Overdue' | 'Upcoming' | 'Unpaid' | 'Cancelled' {
  if (invoice.status === 'Paid' || invoice.status === 'Cancelled' || invoice.status === 'Partial') {
    return invoice.status;
  }
  const due = new Date(invoice.dueDate).getTime();
  if (Number.isNaN(due)) return invoice.status;
  if (due > Date.now()) return 'Upcoming';
  // Nothing in this app ever stores the literal status "Overdue" — an invoice
  // is really overdue once it's still unpaid and its due date has passed.
  return 'Overdue';
}

const TERM_REGEX = /term\s*(\d+)/i;

/**
 * Splits a fee structure's components into per-term invoice amounts.
 * Term-labeled components (e.g. "Tuition Fee - Term 2") go to their own term;
 * every other one-time component (Registration, Admission, Uniform, etc.) is
 * billed with Term 1, matching how schools actually collect those at
 * enrollment/start of year. Returns null when the structure has no
 * term-labeled components, so callers can fall back to a single annual
 * invoice instead of guessing a split.
 */
export function buildTermInvoiceRows(structure: FeeStructure): { term: string; termNumber: number; amount: number; dueDate: string }[] | null {
  const termAmounts = new Map<number, number>();
  let oneTimeTotal = 0;
  for (const c of structure.components) {
    const match = c.name.match(TERM_REGEX);
    if (match) {
      const n = Number(match[1]);
      termAmounts.set(n, (termAmounts.get(n) || 0) + c.amount);
    } else {
      oneTimeTotal += c.amount;
    }
  }
  const termNumbers = Array.from(termAmounts.keys()).sort((a, b) => a - b);
  if (termNumbers.length === 0) return null;

  const DAY = 24 * 60 * 60 * 1000;
  // Term 1 is due soon (the academic year is already underway); later terms
  // are spaced months apart so they surface as "Upcoming" rather than being
  // fabricated as currently due/paid before their real due date arrives.
  const dueOffsetDays: Record<number, number> = { 1: 15, 2: 135, 3: 255 };
  const now = Date.now();

  return termNumbers.map((n, idx) => {
    const tuition = termAmounts.get(n) || 0;
    const amount = idx === 0 ? tuition + oneTimeTotal : tuition;
    const offset = dueOffsetDays[n] ?? (15 + (n - 1) * 120);
    return {
      term: `Term ${n}`,
      termNumber: n,
      amount,
      dueDate: new Date(now + offset * DAY).toISOString(),
    };
  });
}

// Next sequential INV-YYYY-NNNNNN number, shared by every invoice-creating
// path (bulk class, manual single, and the standalone auto-generation
// helpers below) so every invoice in the school shares one unbroken sequence.
// Invoices are school-wide financial records, not private to whichever staff
// account happened to create them — fetching unscoped (no uid) is what
// actually keeps the sequence unbroken across different admin/finance
// accounts; scoping it by creator let two different users both hand out
// "INV-2026-000001", a real duplicate-invoice-number bug.
async function nextInvoiceNumber(_uid: string): Promise<string> {
  const year = new Date().getFullYear();
  const existingInvoices = await smartDb.getAll("Invoice");
  const seqPattern = new RegExp(`^INV-${year}-(\\d+)$`);
  const nextSeq = existingInvoices.reduce((max: number, inv: any) => {
    const m = seqPattern.exec(inv.invoiceNumber || "");
    return m ? Math.max(max, parseInt(m[1], 10)) : max;
  }, 0) + 1;
  return `INV-${year}-${String(nextSeq).padStart(6, "0")}`;
}

/**
 * Auto-generate a flat-amount Admission/SchoolFee invoice for one admissions
 * lead — used both by the manual "Generate Fee Invoice" picker (Collections)
 * and by the automatic triggers (admission form submitted, documents
 * approved). Picks the first Active structure of the matching feeType; if
 * none exists, returns null rather than fabricating an amount — the caller
 * is expected to notify admin so a structure gets created and the lead is
 * picked up manually instead.
 */
export async function createLeadFeeInvoice(input: {
  uid: string;
  leadId: string;
  studentName: string;
  className: string;
  feeType: 'Admission' | 'SchoolFee';
  feeStructureId?: string; // when known (e.g. picked explicitly in the UI)
  dueInDays?: number;
}): Promise<Invoice | null> {
  // FeeStructures are single-tenant admin config, not scoped to whichever uid
  // triggered this call (public admission forms don't have a real admin uid) —
  // fetch unfiltered, same convention AdmissionsContext uses for Leads.
  const structures: FeeStructure[] = await smartDb.getAll("FeeStructure");

  // Admission Fee is a flat one-off charge regardless of grade — same generic
  // Active "Admission" structure for everyone, as before.
  //
  // School Fee is different: it's the student's actual Term 1 tuition for the
  // grade they applied to, so it must come from the real per-grade Tuition
  // structure (same source createFirstTermInvoiceForStudent uses once they're
  // enrolled) rather than a generic flat "SchoolFee" structure that ignores
  // which grade they're joining and any grade-specific components (transport,
  // lab fees, etc.). Falls back to an explicit Active "SchoolFee" structure
  // only if finance hasn't set up a per-grade Tuition structure for this class.
  let structure: FeeStructure | undefined;
  let termAmount: number | null = null;
  let termLabel: { term?: string; termNumber?: number } = {};

  if (input.feeStructureId) {
    structure = structures.find(s => s.id === input.feeStructureId);
  } else if (input.feeType === 'SchoolFee') {
    const tuitionStructure = structures.find(s =>
      s.status === 'Active' && (s.feeType === 'Tuition' || !s.feeType) &&
      (s.className === input.className || s.classId === input.className));
    if (tuitionStructure) {
      const rows = buildTermInvoiceRows(tuitionStructure);
      structure = tuitionStructure;
      if (rows?.[0]) { termAmount = rows[0].amount; termLabel = { term: rows[0].term, termNumber: rows[0].termNumber }; }
    } else {
      structure = structures.find(s => s.status === 'Active' && s.feeType === 'SchoolFee');
    }
  } else {
    structure = structures.find(s => s.status === 'Active' && s.feeType === input.feeType);
  }
  if (!structure) return null;

  const amount = termAmount ?? structure.totalAmount;
  const invoiceNumber = await nextInvoiceNumber(input.uid);
  const dueDate = new Date(Date.now() + (input.dueInDays ?? 7) * 24 * 60 * 60 * 1000).toISOString();

  const record = {
    invoiceNumber,
    studentId: input.leadId,
    studentName: input.studentName,
    classId: input.className,
    className: input.className,
    category: structure.name,
    ...termLabel,
    amount,
    paidAmount: 0,
    dueAmount: amount,
    dueDate,
    status: 'Unpaid' as const,
    penalty: 0,
    feeType: input.feeType,
    linkedLeadId: input.leadId,
    uid: input.uid,
    createdAt: new Date().toISOString(),
  };
  const created: any = await smartDb.create("Invoice", record);
  window.dispatchEvent(new Event("fees-updated"));
  return { ...record, id: created?.id ?? invoiceNumber } as Invoice;
}

/**
 * Auto-generate the Term 1 tuition invoice for one newly-enrolled student —
 * called right after a real Student record is created (AdmissionsContext's
 * enrollLead). Only bills Term 1 (which already bundles one-time components
 * like Registration, per buildTermInvoiceRows) — later terms still come from
 * the normal bulk "Generate Invoices" flow once the whole class is ready.
 * Returns null (no fabrication) when no Active Tuition structure matches
 * this student's grade yet.
 */
export async function createFirstTermInvoiceForStudent(input: {
  uid: string;
  studentId: string;
  studentName: string;
  classId: string;
  className: string;
}): Promise<Invoice | null> {
  const structures: FeeStructure[] = await smartDb.getAll("FeeStructure");
  const structure = structures.find(s =>
    s.status === 'Active' &&
    (s.feeType === 'Tuition' || !s.feeType) &&
    (s.className === input.className || s.classId === input.classId)
  );
  if (!structure) return null;

  const termRows = buildTermInvoiceRows(structure);
  const firstTerm = termRows?.[0] ?? {
    term: undefined as string | undefined,
    termNumber: undefined as number | undefined,
    amount: structure.totalAmount,
    dueDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
  };

  const invoiceNumber = await nextInvoiceNumber(input.uid);
  const record = {
    invoiceNumber,
    studentId: input.studentId,
    studentName: input.studentName,
    classId: input.classId,
    className: structure.className,
    category: structure.name,
    term: firstTerm.term,
    termNumber: firstTerm.termNumber,
    amount: firstTerm.amount,
    paidAmount: 0,
    dueAmount: firstTerm.amount,
    dueDate: firstTerm.dueDate,
    status: 'Unpaid' as const,
    penalty: 0,
    uid: input.uid,
    createdAt: new Date().toISOString(),
  };
  const created: any = await smartDb.create("Invoice", record);
  window.dispatchEvent(new Event("fees-updated"));
  return { ...record, id: created?.id ?? invoiceNumber } as Invoice;
}

/**
 * Auto-generate a Transport fee invoice when a student's route allocation
 * becomes Active. Unlike Admission/SchoolFee/Hostel, there is no central
 * FeeStructure to look up here — Transport already carries a real,
 * deliberately-entered per-student `monthlyFee` on the allocation record
 * itself (it varies by route/distance, so a single flat FeeStructure
 * wouldn't fit). Returns null (no fabrication) if that fee is 0/unset.
 */
export async function createTransportFeeInvoice(input: {
  uid: string;
  studentId: string;
  studentName: string;
  classId: string;
  className: string;
  monthlyFee: number;
  route?: string;
  dueInDays?: number;
}): Promise<Invoice | null> {
  if (!input.monthlyFee || input.monthlyFee <= 0) return null;

  const invoiceNumber = await nextInvoiceNumber(input.uid);
  const dueDate = new Date(Date.now() + (input.dueInDays ?? 7) * 24 * 60 * 60 * 1000).toISOString();
  const record = {
    invoiceNumber,
    studentId: input.studentId,
    studentName: input.studentName,
    classId: input.classId,
    className: input.className,
    category: input.route ? `Transport Fee — ${input.route}` : "Transport Fee",
    amount: input.monthlyFee,
    paidAmount: 0,
    dueAmount: input.monthlyFee,
    dueDate,
    status: 'Unpaid' as const,
    penalty: 0,
    feeType: 'Transport' as const,
    uid: input.uid,
    createdAt: new Date().toISOString(),
  };
  const created: any = await smartDb.create("Invoice", record);
  window.dispatchEvent(new Event("fees-updated"));
  return { ...record, id: created?.id ?? invoiceNumber } as Invoice;
}

/**
 * Auto-generate an Exam fee invoice when a student is given a real seat
 * allocation for an exam that has a fee attached. Like Transport, this
 * reads a real per-exam fee already set on the exam record (ExamRecord.
 * examFee) rather than a central FeeStructure lookup — exam fees vary per
 * exam, not by a fixed structure. Returns null (no fabrication) if the exam
 * has no fee set (the common case — most exams are free).
 */
export async function createExamFeeInvoice(input: {
  uid: string;
  studentId: string;
  studentName: string;
  classId: string;
  className: string;
  examFee: number;
  examName?: string;
  dueInDays?: number;
}): Promise<Invoice | null> {
  if (!input.examFee || input.examFee <= 0) return null;

  const invoiceNumber = await nextInvoiceNumber(input.uid);
  const dueDate = new Date(Date.now() + (input.dueInDays ?? 7) * 24 * 60 * 60 * 1000).toISOString();
  const record = {
    invoiceNumber,
    studentId: input.studentId,
    studentName: input.studentName,
    classId: input.classId,
    className: input.className,
    category: input.examName ? `Exam Fee — ${input.examName}` : "Exam Fee",
    amount: input.examFee,
    paidAmount: 0,
    dueAmount: input.examFee,
    dueDate,
    status: 'Unpaid' as const,
    penalty: 0,
    feeType: 'Exam' as const,
    uid: input.uid,
    createdAt: new Date().toISOString(),
  };
  const created: any = await smartDb.create("Invoice", record);
  window.dispatchEvent(new Event("fees-updated"));
  return { ...record, id: created?.id ?? invoiceNumber } as Invoice;
}

/**
 * Auto-generate a Hostel fee invoice when a student's room allocation
 * becomes Active. Unlike Transport, the hostel module has no real fee
 * amount anywhere on the room/allocation record, so this follows the same
 * FeeStructure-lookup pattern as Admission/SchoolFee: picks the first Active
 * "Hostel" structure matching the room type, or returns null (no
 * fabrication) if finance hasn't configured one yet.
 */
export async function createHostelFeeInvoice(input: {
  uid: string;
  studentId: string;
  studentName: string;
  classId: string;
  className: string;
  roomType?: string;
  dueInDays?: number;
}): Promise<Invoice | null> {
  const structures: FeeStructure[] = await smartDb.getAll("FeeStructure");
  const structure = structures.find(s =>
    s.status === 'Active' && s.feeType === 'Hostel' &&
    (!input.roomType || !s.className || s.className === input.roomType)
  ) ?? structures.find(s => s.status === 'Active' && s.feeType === 'Hostel');
  if (!structure) return null;

  const invoiceNumber = await nextInvoiceNumber(input.uid);
  const dueDate = new Date(Date.now() + (input.dueInDays ?? 7) * 24 * 60 * 60 * 1000).toISOString();
  const record = {
    invoiceNumber,
    studentId: input.studentId,
    studentName: input.studentName,
    classId: input.classId,
    className: input.className,
    category: structure.name,
    amount: structure.totalAmount,
    paidAmount: 0,
    dueAmount: structure.totalAmount,
    dueDate,
    status: 'Unpaid' as const,
    penalty: 0,
    feeType: 'Hostel' as const,
    uid: input.uid,
    createdAt: new Date().toISOString(),
  };
  const created: any = await smartDb.create("Invoice", record);
  window.dispatchEvent(new Event("fees-updated"));
  return { ...record, id: created?.id ?? invoiceNumber } as Invoice;
}

/**
 * Real, per-family delivery for a freshly-generated fee invoice — a private
 * Notification (parent inbox), a private Notice (Announcements feed), and,
 * when the due date is a real date, a private Calendar entry. "Private"
 * here means `recipientStudentId` is set (see announcementAudience.ts):
 * visible only to staff and to this one real family, never broadcast to the
 * whole grade/section the way a normal Notice/CalendarEvent is — Notice and
 * CalendarEvent otherwise have no per-individual targeting, only whole-class
 * or school-wide, so a naive bridge would leak one family's invoice amount
 * to their entire class. Deterministic ids keyed off the invoice id make
 * this safe to call more than once for the same invoice.
 */
export async function notifyFeeInvoiceGenerated(invoice: Invoice, uid: string): Promise<void> {
  const now = new Date().toISOString();
  const due = new Date(invoice.dueDate);
  const dueDateOnly = Number.isNaN(due.getTime()) ? undefined : due.toISOString().split("T")[0];
  const amountText = `QAR ${invoice.amount.toLocaleString()}`;

  await smartDb.create("Notice", {
    title: `Fee invoice generated — ${invoice.category}`,
    content: `Invoice ${invoice.invoiceNumber}: ${amountText} due ${dueDateOnly || "soon"}.`,
    category: "Finance", priority: "Medium", status: "Published",
    targetAudience: "Parents", targetClass: "",
    recipientStudentId: invoice.studentId,
    postedBy: "Finance", date: now.split("T")[0], views: 0, uid,
  }, `notice-invoice-${invoice.id}`).catch(() => {});

  if (dueDateOnly) {
    await smartDb.create("CalendarEvent", {
      title: `Fee due — ${invoice.category}`,
      description: `Invoice ${invoice.invoiceNumber}: ${amountText}`,
      date: dueDateOnly, time: "09:00 AM", location: "", category: "Finance", color: "amber",
      status: "Published", targetAudience: "Parents", targetClass: "",
      recipientStudentId: invoice.studentId,
      source: "Finance", createdBy: uid,
    }, `calendar-invoice-${invoice.id}`).catch(() => {});
  }

  await smartDb.create("Notification", {
    id: `notif-invoice-parent-${invoice.id}`,
    uid, audienceRole: "parent", studentId: invoice.studentId, category: "finance",
    type: "invoice_generated", title: "New Fee Invoice",
    message: `A new invoice (${invoice.category}) for ${amountText} has been generated, due ${dueDateOnly || "soon"}.`,
    createdAt: now, time: now, read: false,
  }, `notif-invoice-parent-${invoice.id}`).catch(() => {});
}

/**
 * When an Admission/SchoolFee invoice is paid IN FULL, advance the linked
 * Admissions Lead's pipeline stage the same way the old FinancePendingPayment
 * "Confirm Payment Received" flow used to — now driven by the real invoice
 * payment (Collections, or a parent/student self-paying via their own portal)
 * instead of a separate manual confirmation step. Plain exported function
 * (not part of the useFees() hook) so every payment-completion call site —
 * useFees.ts's own collectFee, and the parent/student portals' own
 * finalizeInvoicePayment (which write directly to the Invoice table and don't
 * go through this hook) — can call it with just the paid invoice in hand.
 */
export async function advanceLeadOnFeeInvoicePaid(invoice: Invoice, paymentMethod?: string): Promise<void> {
  if (!invoice.linkedLeadId) return;
  if (invoice.feeType !== 'Admission' && invoice.feeType !== 'SchoolFee') return;
  try {
    const now = new Date().toISOString();
    if (invoice.feeType === 'Admission') {
      await smartDb.update("Lead", invoice.linkedLeadId, {
        status: "Payment Done",
        admissionFeesPaid: true,
        paymentDate: now,
        invoiceNumber: invoice.invoiceNumber,
        updatedAt: now,
      });
    } else {
      await smartDb.update("Lead", invoice.linkedLeadId, {
        status: "Section Allocation",
        schoolFeesPaid: true,
        schoolFeePaymentDate: now,
        schoolFeesInvoice: invoice.invoiceNumber,
        updatedAt: now,
      });
    }

    // Email the parent a real payment receipt, and let finance/admin know
    // the lead advanced automatically — no manual "confirm payment" step.
    const lead: any = await smartDb.getOne("Lead", invoice.linkedLeadId).catch(() => null);
    const paymentType = invoice.feeType === 'Admission' ? 'Admission Fee' : 'Annual School Fee';
    if (lead?.email) {
      await sendInvoiceEmail({
        to: lead.email,
        toName: lead.parentName || invoice.studentName,
        studentName: invoice.studentName,
        invoiceNo: invoice.invoiceNumber,
        amount: invoice.amount,
        paymentType,
        paymentMethod: paymentMethod || "—",
        paidAt: now,
      }).catch(() => {});
    }
    const adminNotifId = `notif_${Date.now()}_admin_${invoice.id}`;
    await smartDb.create("Notification", {
      id: adminNotifId,
      uid: invoice.uid,
      audienceRole: "admin",
      type: "payment_confirmed",
      category: "finance",
      title: `${paymentType} Paid`,
      message: `${invoice.studentName} paid ${invoice.invoiceNumber} (${paymentType}) — lead automatically advanced to "${invoice.feeType === 'Admission' ? 'Payment Done' : 'Section Allocation'}".`,
      createdAt: now,
      time: now,
      read: false,
      invoiceNumber: invoice.invoiceNumber,
    }, adminNotifId).catch(() => {});
  } catch (error) {
    console.error("Failed to advance admissions lead after fee invoice payment:", error);
  }
}

export function useFees() {
  const { user } = useAuth();
  const { settings: financialSettings } = useFinancialSettings();
  const queryClient = useQueryClient();
  const queryKey = ["fees-data"];

  // Called from ~8 places (Fees Management, parent/student fee pages, and
  // several dialogs) — each used to independently fire 3 parallel
  // smartDb.getAll calls (FeeStructure/FeeDiscount/Invoice) on mount.
  // react-query shares one fetch and one cache entry across all of them.
  const { data, isLoading: loading } = useQuery({
    queryKey,
    queryFn: async () => {
      // Unscoped — fee structures, discounts, and invoices are school-wide
      // financial records shared across every finance/admin account, not
      // private to whichever staff member happened to create them. Scoping
      // by creator uid made one admin's invoices (and, worse, the shared
      // invoice-number sequence) invisible to every other admin/accountant.
      const [structures, discounts, invs] = await Promise.all([
        smartDb.getAll("FeeStructure"),
        smartDb.getAll("FeeDiscount"),
        smartDb.getAll("Invoice")
      ]);
      return {
        structures: structures as FeeStructure[],
        discounts: discounts as FeeDiscount[],
        invoices: invs.map((i: any) => {
          const amount = Number(i.amount) || 0;
          const paidAmount = i.paidAmount !== undefined ? Number(i.paidAmount) : (i.status === 'Paid' ? amount : 0);
          const dueAmount = i.dueAmount !== undefined ? Number(i.dueAmount) : (i.status === 'Unpaid' || i.status === 'Overdue' ? amount : (i.status === 'Paid' ? 0 : amount - paidAmount));
          return { ...i, amount, paidAmount, dueAmount };
        }) as Invoice[],
      };
    },
    enabled: !!user,
  });

  const feeStructures = data?.structures ?? [];
  const feeDiscounts = data?.discounts ?? [];
  const invoices = data?.invoices ?? [];
  const fetchFeesData = () => queryClient.invalidateQueries({ queryKey });

  useEffect(() => {
    // Refetch whenever any invoice/payment mutation happens anywhere in the
    // app (Collections, Due Tracking, parent portal payment, etc.) so every
    // consumer of useFees() stays in sync without a manual page reload.
    window.addEventListener("fees-updated", fetchFeesData);
    return () => window.removeEventListener("fees-updated", fetchFeesData);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const createFeeStructure = async (data: Omit<FeeStructure, 'id' | 'uid' | 'createdAt'>) => {
    if (!user) return;
    try {
      await smartDb.create("FeeStructure", {
        ...data,
        uid: user.uid,
        createdAt: new Date().toISOString()
      });
      fetchFeesData();
      toast.success("Fee structure created successfully");
    } catch (error) {
      handleFirestoreError(error, OperationType.CREATE, "FeeStructure");
    }
  };

  const updateFeeStructure = async (id: string, data: Partial<Omit<FeeStructure, 'id' | 'uid' | 'createdAt'>>) => {
    if (!user) return;
    try {
      await smartDb.update("FeeStructure", id, { ...data, updatedAt: new Date().toISOString() });
      fetchFeesData();
      toast.success("Fee structure updated successfully");
    } catch (error) {
      handleFirestoreError(error, OperationType.UPDATE, "FeeStructure");
    }
  };

  const deleteFeeStructure = async (id: string) => {
    if (!user) return;
    try {
      await smartDb.delete("FeeStructure", id);
      fetchFeesData();
      toast.success("Fee structure deleted");
    } catch (error) {
      handleFirestoreError(error, OperationType.DELETE, "FeeStructure");
    }
  };

  /**
   * Bulk-create fee structures from an imported file (one row per grade).
   * Returns { created, skipped } so the caller can show an accurate summary —
   * rows are skipped (not silently fabricated) when they don't resolve to a
   * real class or have no usable amount, rather than inventing a classId.
   */
  const bulkImportFeeStructures = async (
    rows: Omit<FeeStructure, 'id' | 'uid' | 'createdAt'>[]
  ): Promise<{ created: number; skipped: number }> => {
    if (!user) return { created: 0, skipped: rows.length };
    let created = 0;
    let skipped = 0;
    for (const row of rows) {
      if (!row.classId || !row.components?.length) { skipped++; continue; }
      try {
        await smartDb.create("FeeStructure", {
          ...row,
          uid: user.uid,
          createdAt: new Date().toISOString(),
        });
        created++;
      } catch (error) {
        console.error("Error importing fee structure row:", row, error);
        skipped++;
      }
    }
    fetchFeesData();
    return { created, skipped };
  };

  const generateInvoicesForClass = async (classId: string, feeStructureId: string) => {
    if (!user) return;
    try {
      const structure = feeStructures.find(s => s.id === feeStructureId);
      if (!structure) throw new Error("Fee structure not found");

      // Student.classId is populated at enrollment with the grade LABEL (e.g. "Grade 5"),
      // not the Class document's auto-generated id — so match on the fee structure's
      // human-readable className (and each student's grade field) instead of the raw
      // classId, which would otherwise never match any real student record.
      //
      // Unscoped: Student.uid is stamped with whichever staff account created
      // the row (see localDb.ts), not a real ownership boundary — scoping by
      // the CURRENT user's uid here would silently skip every student some
      // other admin enrolled, same convention StudentContext.tsx already uses.
      const students = await smartDb.getAll("Student") as Student[];
      const classStudents = students.filter((s: Student) =>
        s.classId === classId ||
        s.classId === structure.className ||
        (s as any).grade === structure.className
      );

      if (classStudents.length === 0) {
        toast.error(`No students found in ${structure.className}. Check that students are enrolled with a matching grade.`);
        return;
      }

      // Prefer a real per-term breakdown (Term 1/2/3) when the structure has
      // term-labeled components; otherwise fall back to one annual invoice.
      const termRows = buildTermInvoiceRows(structure);
      const rows = termRows ?? [{
        term: undefined,
        termNumber: undefined,
        amount: structure.totalAmount,
        dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
      }];

      // Real per-student discount calculation (Strategy pattern —
      // src/services/fee/FeeCalculator.ts) — scholarship/sibling/staff-child
      // discounts previously existed only as data-entry records, never
      // actually applied to an invoice amount. Fetched once for the whole
      // batch rather than per-student.
      const [staffForDiscounts, scholarshipsForDiscounts] = await Promise.all([
        smartDb.getAll("Staff") as Promise<Staff[]>,
        smartDb.getAll("Scholarship") as Promise<ScholarshipRecord[]>,
      ]);
      const feeCalculator = createDefaultFeeCalculator(financialSettings.maxCombinedDiscountPct);
      const discountResultByStudentId = new Map(classStudents.map((student) => [
        student.id,
        feeCalculator.computeInvoice(structure.totalAmount, {
          student,
          allStudents: students,
          staff: staffForDiscounts,
          scholarships: scholarshipsForDiscounts,
          discountDefinitions: feeDiscounts as unknown as FeeDiscountDefinition[],
        }),
      ]));

      // Sequential invoice numbering (INV-YYYY-NNNNNN) instead of a random
      // suffix — most jurisdictions require invoices to be numbered in an
      // unbroken sequence for tax filing. Computed from the current max
      // sequence in this year, then incremented synchronously for every
      // invoice in this batch so none collide. Unscoped for the same reason
      // as nextInvoiceNumber() above — the sequence is school-wide.
      const year = new Date().getFullYear();
      const existingInvoices = await smartDb.getAll("Invoice");
      const seqPattern = new RegExp(`^INV-${year}-(\\d+)$`);
      let nextSeq = existingInvoices.reduce((max: number, inv: any) => {
        const m = seqPattern.exec(inv.invoiceNumber || "");
        return m ? Math.max(max, parseInt(m[1], 10)) : max;
      }, 0) + 1;
      const nextInvoiceNumber = () => `INV-${year}-${String(nextSeq++).padStart(6, "0")}`;

      const batchPromises = classStudents.flatMap((student: Student) => {
        // Same proportional reduction applied to every term row, so a
        // termed structure's rows still sum to the student's real
        // discounted total rather than each row being discounted
        // independently (which could compound rounding oddities across terms).
        const discountResult = discountResultByStudentId.get(student.id);
        const discountRatio = discountResult && structure.totalAmount > 0
          ? discountResult.finalAmount / structure.totalAmount
          : 1;

        return rows.map(row => {
          const invoiceNumber = nextInvoiceNumber();
          const discountedAmount = Math.round(row.amount * discountRatio);
          return smartDb.create("Invoice", {
            invoiceNumber,
            studentId: student.id,
            studentName: student.name,
            classId: student.classId,
            className: structure.className,
            category: structure.name,
            term: row.term,
            termNumber: row.termNumber,
            baseAmount: row.amount,
            amount: discountedAmount,
            // Real applied-discount audit trail — visible on the invoice so a
            // parent/finance user can see exactly why the amount is lower
            // than the fee structure's list price, not just a smaller number
            // with no explanation.
            discountAmount: row.amount - discountedAmount,
            appliedDiscounts: discountResult?.appliedRules.map((r) => r.label) ?? [],
            paidAmount: 0,
            dueAmount: discountedAmount,
            dueDate: row.dueDate,
            status: 'Unpaid',
            penalty: 0,
            uid: user.uid,
            createdAt: new Date().toISOString()
          });
        });
      });

      await Promise.all(batchPromises);
      fetchFeesData();
      window.dispatchEvent(new Event("fees-updated"));

      // Notify each affected student and their parent(s) in-app. Targeted the
      // same way parent fee reminders are (see feeReminderEngine.ts):
      // recipientUid = the student's own id for the student portal, and each
      // parent's email for the parent portal (there's no separately-stored
      // parent account uid — email is how parent sessions are identified).
      const termLabel = rows.length > 1 ? `${rows.length} term invoices` : "an invoice";
      await Promise.allSettled(
        classStudents.flatMap((student: any) => {
          const notifId = `notif_${Date.now()}_${student.id}`;
          const message = `${termLabel} generated for ${student.name} — ${structure.name} (${structure.className}). First due ${new Date(rows[0].dueDate).toLocaleDateString()}.`;
          const recipients = [
            student.id,
            ...[student.fatherEmail, student.motherEmail, student.guardianEmail].filter(Boolean),
          ];
          return recipients.map((recipientUid, i) =>
            smartDb.create(
              "Notification",
              {
                id: `${notifId}_${i}`,
                recipientUid,
                type: "invoice_generated",
                title: "New Fee Invoice",
                message,
                createdAt: new Date().toISOString(),
                time: new Date().toISOString(),
                read: false,
              },
              `${notifId}_${i}`,
            )
          );
        })
      );

      toast.success(
        `Invoices generated for ${classStudents.length} students` +
        (rows.length > 1 ? ` (${rows.length} term invoices each)` : '') +
        " — students and parents notified"
      );
    } catch (error) {
      console.error("Error generating invoices:", error);
      toast.error("Failed to generate invoices");
    }
  };

  /**
   * Generate ONE real invoice for a single admissions lead — the manual
   * "Generate Invoice" action a finance user takes for Admission/School Fee
   * structures, replacing the old auto-created FinancePendingPayment record.
   * Uses the same sequential INV-YYYY-NNNNNN numbering as bulk class invoices
   * so admission/school fee invoices share one unbroken sequence with every
   * other invoice, not a separate random one.
   */
  const generateSingleInvoice = async (input: {
    studentId: string;
    studentName: string;
    classId?: string;
    className: string;
    feeStructureId: string;
    feeType: 'Admission' | 'SchoolFee';
    linkedLeadId?: string;
    dueInDays?: number;
    recipientEmail?: string; // parent/lead email — sends the "please pay" invoice notice when known
  }): Promise<Invoice | undefined> => {
    if (!user) return;
    try {
      const invoice = await createLeadFeeInvoice({
        uid: user.uid,
        leadId: input.linkedLeadId || input.studentId,
        studentName: input.studentName,
        className: input.className,
        feeType: input.feeType,
        feeStructureId: input.feeStructureId,
        dueInDays: input.dueInDays,
      });
      if (!invoice) { toast.error("Fee structure not found"); return; }

      fetchFeesData();

      await smartDb.create("Notification", {
        recipientUid: input.studentId,
        type: "invoice_generated",
        title: input.feeType === 'Admission' ? "Admission Fee Invoice" : "School Fee Invoice",
        message: `${invoice.category} invoice ${invoice.invoiceNumber} generated for ${input.studentName} — due ${new Date(invoice.dueDate).toLocaleDateString()}.`,
        createdAt: new Date().toISOString(),
        time: new Date().toISOString(),
        read: false,
      }).catch(() => {});

      if (input.recipientEmail) {
        await sendInvoiceGeneratedEmail({
          to: input.recipientEmail,
          toName: input.studentName,
          studentName: input.studentName,
          invoiceNo: invoice.invoiceNumber,
          amount: invoice.amount,
          paymentType: input.feeType === 'Admission' ? 'Admission Fee' : 'Annual School Fee',
          dueDate: invoice.dueDate,
        }).catch(() => {});
      }

      toast.success(`${invoice.invoiceNumber} generated for ${input.studentName}`);
      return invoice;
    } catch (error) {
      console.error("Error generating single invoice:", error);
      toast.error("Failed to generate invoice");
    }
  };

  const updateInvoiceStatus = async (invoiceId: string, status: Invoice['status']) => {
    try {
      await smartDb.update("Invoice", invoiceId, { status });
      fetchFeesData();
      window.dispatchEvent(new Event("fees-updated"));
      toast.success("Invoice status updated");
    } catch (error) {
      handleFirestoreError(error, OperationType.UPDATE, "Invoice");
    }
  };

  /**
   * Recompute + persist an invoice's late fee (penalty) and derived due amount.
   * Silent (no toast) since this runs automatically on every Due Tracking load,
   * not from a direct user action — surfacing a toast per invoice would be noisy.
   */
  const updateInvoicePenalty = async (invoiceId: string, penalty: number) => {
    try {
      const invoice = invoices.find(inv => inv.id === invoiceId);
      if (!invoice) return;
      const dueAmount = Math.max(0, invoice.amount + penalty - invoice.paidAmount);
      await smartDb.update("Invoice", invoiceId, { penalty, dueAmount });
      fetchFeesData();
    } catch (error) {
      console.error("Error updating invoice penalty:", error);
    }
  };

  const collectFee = async (invoiceId: string, amount: number, paymentMethod: string, date: string): Promise<Invoice | undefined> => {
    if (!user) return;

    try {
      const invoice = invoices.find(inv => inv.id === invoiceId);
      if (!invoice) throw new Error("Invoice not found");

      const newPaidAmount = (invoice.paidAmount || 0) + amount;
      const newDueAmount = Math.max(0, (invoice.amount + (invoice.penalty || 0)) - newPaidAmount);
      const newStatus: Invoice['status'] = newDueAmount === 0 ? 'Paid' : 'Partial';

      // 1. Update Invoice
      await smartDb.update("Invoice", invoiceId, {
        paidAmount: newPaidAmount,
        dueAmount: newDueAmount,
        status: newStatus,
        updatedAt: new Date().toISOString()
      });

      // 2. Record Revenue
      await smartDb.create("StudentRevenue", {
        student: invoice.studentName,
        studentId: invoice.studentId,
        invoiceId: invoiceId,
        amount: amount,
        category: "Tuition Fee",
        date: date,
        paymentMethod: paymentMethod,
        status: "Paid",
        uid: user.uid,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      });

      const paidInvoice = { ...invoice, paidAmount: newPaidAmount, dueAmount: newDueAmount, status: newStatus };
      // If this was an Admission/School Fee invoice paid in full, advance the
      // linked admissions lead the same way the old manual "Confirm Payment
      // Received" step used to — automatically, from the real payment.
      if (newStatus === 'Paid') await advanceLeadOnFeeInvoicePaid(paidInvoice, paymentMethod);

      fetchFeesData();
      // Notify StudentContext so the student's fee status / Pending Fees filter refreshes.
      window.dispatchEvent(new Event("fees-updated"));
      toast.success(`Payment of ${amount} recorded for ${invoice.studentName}`);
      return paidInvoice;
    } catch (error) {
      handleFirestoreError(error, OperationType.WRITE, "Invoice/StudentRevenue");
      throw error;
    }
  };

  const createFeeDiscount = async (data: Omit<FeeDiscount, 'id' | 'uid' | 'createdAt'>) => {
    if (!user) return;
    try {
      await smartDb.create("FeeDiscount", {
        ...data,
        uid: user.uid,
        createdAt: new Date().toISOString()
      });
      fetchFeesData();
      toast.success("Fee discount created successfully");
    } catch (error) {
      handleFirestoreError(error, OperationType.CREATE, "FeeDiscount");
    }
  };

  return {
    feeStructures,
    feeDiscounts,
    invoices,
    loading,
    createFeeStructure,
    updateFeeStructure,
    deleteFeeStructure,
    bulkImportFeeStructures,
    createFeeDiscount,
    generateInvoicesForClass,
    generateSingleInvoice,
    updateInvoiceStatus,
    updateInvoicePenalty,
    collectFee
  };
}
