// ── Phase 3: AI Copilot write actions ───────────────────────────────────────
// Everything the assistant can DO instead of just report. Every action here
// is deterministic — the proposal preview (who/what/how many) is computed
// straight from real ERP data, never generated by the LLM — so what the user
// confirms is exactly what will execute. Gated per persona's allowedActions
// (see aiPlaybook.ts) and always requires an explicit Confirm click (see
// useAssistantChat.ts) before any write happens. Deliberately NO finance/
// payroll/invoice actions — the Copilot never touches fees, invoices, payroll,
// or bank data (see aiPlaybook.ts's SYSTEM_PROMPT "You cannot" list).
import { smartDb } from "@/lib/localDb";
import { getAllReportCards, saveReportCards, type ReportCardRecord } from "@/lib/reportCardStore";

export interface ActionPreviewRow { label: string; value: string }
export type ActionKind = "publish-report-cards" | "create-assignment" | "leave-decision" | "send-announcement";

export interface ActionProposal {
  kind: ActionKind;
  title: string;
  description: string;
  previewRows: ActionPreviewRow[];
  confirmLabel: string;
  run: () => Promise<{ success: boolean; message: string }>;
}

export interface ActionError { error: string }

interface StudentRecord {
  id: string; name: string; grade?: string; section?: string; email?: string;
}

const norm = (s?: string) => (s || "").toLowerCase().trim().replace(/^grade\s*/i, "");

// ── 1. Publish report cards ─────────────────────────────────────────────────

const PUBLISH_RC_PATTERN = /publish\s*(the\s*)?(report\s*card|result)/i;
export function isPublishReportCardsActionIntent(text: string): boolean {
  return PUBLISH_RC_PATTERN.test(text.trim());
}

function parseGradeSection(text: string): { grade?: string; section?: string } {
  const gradeMatch = text.match(/grade\s*([a-z0-9-]+)/i);
  const sectionMatch = text.match(/section\s*([a-z])/i);
  return { grade: gradeMatch ? gradeMatch[1] : undefined, section: sectionMatch ? sectionMatch[1].toUpperCase() : undefined };
}

export async function buildPublishReportCardsProposal(text: string): Promise<ActionProposal | ActionError> {
  const { grade, section } = parseGradeSection(text);
  const approved = getAllReportCards().filter(r => r.status === "approved");
  const scoped = approved.filter(r => {
    if (grade && norm(r.grade) !== norm(grade)) return false;
    if (section && (r.section || "").toUpperCase() !== section) return false;
    return true;
  });

  if (scoped.length === 0) {
    return {
      error: grade
        ? `No approved (unpublished) report cards found for Grade ${grade}${section ? ` Section ${section}` : ""} — nothing to publish.`
        : "No approved report cards are waiting to be published right now.",
    };
  }

  const scopeLabel = grade ? `Grade ${grade}${section ? ` Section ${section}` : ""}` : "all grades (every approved report card school-wide)";
  return {
    kind: "publish-report-cards",
    title: "Publish report cards",
    description: `Publish ${scoped.length} approved report card(s) for ${scopeLabel} to students and parents.`,
    previewRows: [
      { label: "Scope", value: scopeLabel },
      { label: "Report cards to publish", value: String(scoped.length) },
      { label: "Students", value: scoped.slice(0, 8).map(r => r.name).join(", ") + (scoped.length > 8 ? `, +${scoped.length - 8} more` : "") },
    ],
    confirmLabel: `Publish ${scoped.length} report card(s)`,
    run: async () => {
      const updated: ReportCardRecord[] = scoped.map(r => ({ ...r, publishedToStudents: true, publishedToParents: true, status: "published" }));
      saveReportCards(updated);
      return { success: true, message: `Published ${updated.length} report card(s) for ${scopeLabel}. Students and parents have been notified.` };
    },
  };
}

// ── 2. Create assignment + notify class ─────────────────────────────────────

const CREATE_ASSIGNMENT_PATTERN = /create\s*(an\s*)?assignment|assign\s*homework/i;
export function isCreateAssignmentActionIntent(text: string): boolean {
  return CREATE_ASSIGNMENT_PATTERN.test(text.trim());
}

export async function buildCreateAssignmentProposal(
  text: string,
  creatorUid: string,
  /** When set (Teacher persona), the assignment is forced to the teacher's own
   *  class regardless of what grade/section the message mentions — a teacher
   *  can never create an assignment for someone else's class. */
  scope?: { grade: string; section: string },
): Promise<ActionProposal | ActionError> {
  const titleMatch = text.match(/["“]([^"”]+)["”]/);
  const gradeMatch = text.match(/grade\s*([a-z0-9-]+)/i);
  const sectionMatch = text.match(/section\s*([a-z])/i);
  const subjectMatch = text.match(/subject\s+([a-z][a-z\s]*?)(?=,|\.|due|grade|section|$)/i);
  const dueMatch = text.match(/due\s+(\d{4}-\d{2}-\d{2})/i);

  const missing: string[] = [];
  if (!titleMatch) missing.push('a title in quotes, e.g. "Algebra Worksheet 3"');
  if (!scope && !gradeMatch) missing.push('the grade, e.g. "Grade 8"');
  if (!scope && !sectionMatch) missing.push('the section, e.g. "Section B"');
  if (!subjectMatch) missing.push('the subject, e.g. "subject Math"');
  if (!dueMatch) missing.push('a due date in YYYY-MM-DD format, e.g. "due 2026-07-10"');

  if (missing.length > 0) {
    return {
      error: `To create an assignment I need: ${missing.join("; ")}.\n\nExample: Create assignment "Algebra Worksheet 3"${scope ? "" : " for Grade 8 Section B"}, subject Math, due 2026-07-10`,
    };
  }

  if (scope) {
    const requestedGrade = gradeMatch ? `Grade ${gradeMatch[1].replace(/^grade\s*/i, "")}` : undefined;
    const requestedSection = sectionMatch ? sectionMatch[1].toUpperCase() : undefined;
    if ((requestedGrade && norm(requestedGrade) !== norm(scope.grade)) || (requestedSection && requestedSection !== scope.section.toUpperCase())) {
      return { error: `You can only create assignments for your own class — Grade ${scope.grade.replace(/^grade\s*/i, "")} Section ${scope.section}.` };
    }
  }

  const grade = scope ? `Grade ${scope.grade.replace(/^grade\s*/i, "")}` : `Grade ${gradeMatch![1].replace(/^grade\s*/i, "")}`;
  const section = scope ? scope.section.toUpperCase() : sectionMatch![1].toUpperCase();
  const subject = subjectMatch![1].trim();
  const dueDate = dueMatch![1];
  const title = titleMatch![1];
  const classId = `${grade}-${section}`;

  const students = (await smartDb.getAll("Student").catch(() => [])) as StudentRecord[];
  const classStudents = students.filter(s => norm(s.grade) === norm(grade) && (s.section || "").toUpperCase() === section);

  return {
    kind: "create-assignment",
    title: "Create assignment",
    description: `Create "${title}" for ${grade} Section ${section} (${subject}), due ${dueDate}, and notify the class.`,
    previewRows: [
      { label: "Title", value: title },
      { label: "Class", value: `${grade} — Section ${section}` },
      { label: "Subject", value: subject },
      { label: "Due date", value: dueDate },
      { label: "Students to notify", value: String(classStudents.length) },
    ],
    confirmLabel: "Create & notify class",
    run: async () => {
      const assignmentId = `ai-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`;
      await smartDb.create("Assignment", {
        title, description: "Created via Student Diwan Assistant.", dueDate, classId, subject,
        status: "Active", submissionsCount: 0, uid: creatorUid, createdAt: new Date().toISOString(),
      }, assignmentId);

      let notified = 0;
      for (const s of classStudents) {
        const notifId = `assign-${assignmentId}-${s.id}`;
        try {
          await smartDb.create("Notification", {
            id: notifId, recipientUid: s.email || undefined, category: "student", entity: "Assignment",
            type: "assignment_created", title: `New assignment: ${title}`,
            message: `${subject} — due ${dueDate}.`, classId, subject,
            createdAt: new Date().toISOString(), time: new Date().toISOString(), read: false,
            redirectUrl: `/student/assignments?id=${assignmentId}`,
          }, notifId);
          notified += 1;
        } catch { /* best-effort per-student notify */ }
      }
      return { success: true, message: `Created "${title}" for ${grade} Section ${section} and notified ${notified} student(s).` };
    },
  };
}

// ── 3. Approve / reject a leave request (Phase 4) ───────────────────────────
// Reuses the SAME approveLeaveStep/rejectLeave functions the manual HR/Admin
// leave-approval UI calls (src/contexts/LeaveContext.tsx) — the approval
// chain logic itself is never duplicated here, only matched against by name.

export interface LeaveRequestLite {
  id: string; staffName: string; type: string; startDate: string; endDate: string;
  reason?: string; status: string; category?: "staff" | "student"; days?: number;
  approvalChain?: { label: string; status: string }[]; currentStep?: number;
}

const LEAVE_ACTION_PATTERN = /\b(approve|reject)\b.{0,20}\bleave\b/i;
export function isLeaveActionIntent(text: string): boolean {
  return LEAVE_ACTION_PATTERN.test(text.trim());
}

export async function buildLeaveActionProposal(
  text: string,
  leaves: LeaveRequestLite[],
  approveFn: (id: string, remark?: string) => Promise<void>,
  rejectFn: (id: string, remark?: string) => Promise<void>,
): Promise<ActionProposal | ActionError> {
  const decision: "approve" | "reject" = /reject/i.test(text) ? "reject" : "approve";
  const nameMatch = text.match(/for\s+([a-z][a-z\s.'-]*)/i);
  const name = nameMatch ? nameMatch[1].trim().replace(/[.,]+$/, "") : undefined;

  const pending = leaves.filter(l => (l.status || "").toLowerCase() === "pending");
  if (pending.length === 0) {
    return { error: "There are no pending leave requests right now." };
  }

  let candidates = pending;
  if (name) {
    candidates = pending.filter(l => l.staffName.toLowerCase().includes(name.toLowerCase()));
    if (candidates.length === 0) {
      return { error: `No pending leave request found for "${name}". Pending requests are from: ${pending.map(l => l.staffName).join(", ")}.` };
    }
  } else if (pending.length > 1) {
    return { error: `There are ${pending.length} pending leave requests — please specify whose, e.g. "${decision} leave for ${pending[0].staffName}". Pending: ${pending.map(l => l.staffName).join(", ")}.` };
  }
  if (candidates.length > 1) {
    return { error: `Multiple pending leave requests match "${name}": ${candidates.map(l => l.staffName).join(", ")}. Please be more specific.` };
  }

  const leave = candidates[0];
  const stepIdx = leave.currentStep ?? 0;
  const currentApprover = leave.approvalChain?.[stepIdx]?.label ?? "current approver";

  return {
    kind: "leave-decision",
    title: decision === "approve" ? "Approve leave request" : "Reject leave request",
    description: `${decision === "approve" ? "Approve" : "Reject"} ${leave.staffName}'s ${leave.type} request (${leave.startDate} → ${leave.endDate}).`,
    previewRows: [
      { label: "Requester", value: leave.staffName },
      { label: "Leave type", value: leave.type },
      { label: "Dates", value: `${leave.startDate} → ${leave.endDate}${leave.days ? ` (${leave.days} day${leave.days === 1 ? "" : "s"})` : ""}` },
      { label: "Reason", value: leave.reason || "—" },
      { label: "Current step", value: currentApprover },
    ],
    confirmLabel: decision === "approve" ? "Approve" : "Reject",
    run: async () => {
      if (decision === "approve") {
        await approveFn(leave.id, "Approved via Student Diwan Assistant.");
        return { success: true, message: `Approved ${leave.staffName}'s ${leave.type} request${(leave.approvalChain?.length ?? 1) > stepIdx + 1 ? ` — forwarded to the next approver.` : "."}` };
      }
      await rejectFn(leave.id, "Rejected via Student Diwan Assistant.");
      return { success: true, message: `Rejected ${leave.staffName}'s ${leave.type} request.` };
    },
  };
}

// ── 4. Send announcement (Phase 4) ──────────────────────────────────────────
// Reuses addNotice() from NoticeContext.tsx — same audience/targetClass shape
// the manual Announcements page writes, so filterAnnouncementsForViewer()
// (src/lib/announcementAudience.ts) applies identically either way.

export interface NoticeDraft {
  title: string; content: string; category: "General" | "Academic" | "Finance" | "Event" | "Urgent";
  priority: "Low" | "Medium" | "High"; status: "Published"; targetAudience: "All" | "Students" | "Staff" | "Parents";
  targetClass?: string;
}

const SEND_ANNOUNCEMENT_PATTERN = /send\s*(an\s*)?announcement|post\s*(a\s*)?notice|create\s*(an\s*)?announcement/i;
export function isSendAnnouncementActionIntent(text: string): boolean {
  return SEND_ANNOUNCEMENT_PATTERN.test(text.trim());
}

export async function buildSendAnnouncementProposal(
  text: string,
  addNotice: (n: NoticeDraft) => Promise<void>,
): Promise<ActionProposal | ActionError> {
  const quoted = [...text.matchAll(/["“]([^"”]+)["”]/g)].map(m => m[1]);
  const title = quoted[0];
  const content = quoted[1];
  const audienceMatch = text.match(/to\s+(all|students|staff|parents)\b/i);
  const gradeMatch = text.match(/grade\s*([a-z0-9-]+)/i);
  const sectionMatch = text.match(/section\s*([a-z])/i);

  const missing: string[] = [];
  if (!title) missing.push('a title in quotes, e.g. "Sports Day Postponed"');
  if (!content) missing.push('the message in a second set of quotes, e.g. "Sports Day is moved to July 15."');
  if (!audienceMatch) missing.push('who it\'s for: "to All", "to Students", "to Staff", or "to Parents"');

  if (missing.length > 0) {
    return {
      error: `To send an announcement I need: ${missing.join("; ")}.\n\nExample: Send announcement "Sports Day Postponed" saying "Sports Day is moved to July 15." to Students` +
        (gradeMatch ? "" : ' for Grade 8 Section B (optional, to target one class)'),
    };
  }

  const audienceRaw = audienceMatch![1].toLowerCase();
  const targetAudience = (audienceRaw.charAt(0).toUpperCase() + audienceRaw.slice(1)) as NoticeDraft["targetAudience"];
  const targetClass = gradeMatch ? `Grade ${gradeMatch[1].replace(/^grade\s*/i, "")}${sectionMatch ? `-${sectionMatch[1].toUpperCase()}` : ""}` : undefined;

  return {
    kind: "send-announcement",
    title: "Send announcement",
    description: `Publish "${title}" to ${targetAudience}${targetClass ? ` (${targetClass})` : ""}.`,
    previewRows: [
      { label: "Title", value: title! },
      { label: "Message", value: content! },
      { label: "Audience", value: targetAudience + (targetClass ? ` — ${targetClass}` : "") },
      { label: "Category", value: "General" },
    ],
    confirmLabel: "Publish announcement",
    run: async () => {
      await addNotice({
        title: title!, content: content!, category: "General", priority: "Medium",
        status: "Published", targetAudience, targetClass,
      });
      return { success: true, message: `Published "${title}" to ${targetAudience}${targetClass ? ` (${targetClass})` : ""}.` };
    },
  };
}
